
###
GET http://localhost:8080/get
Content-Type: application/json
Authorization: Basic user password

###
GET http://localhost:8080/ads/asddsfsdf/comment
Content-Type: application/json
Authorization: Basic user password

###
POST http://localhost:8080/login
Content-Type: application/json

{
   "username": "user",
   "password": "password",
   "firstName":  " asdad",
   "lastName": " asdad",
   "phone":  " asdad"
}

###
POST http://localhost:8080/register
Content-Type: application/json

{
  "username": "user12",
  "password": "password1"
}

###
GET http://localhost:8080/ads/me
Content-Type: application/json
Authorization: Basic user password

###
GET http://localhost:8080/users/me
Content-Type: application/json
Authorization: Basic user@gmail.com password

###
PATCH http://localhost:8080/users/me
Content-Type: application/json
Authorization: Basic user password

{
  "phone": "33333",
  "lastName": "Ivanov",
  "firstName": "Ivan",
  "email": "user",
  "id": 1
}

###
GET http://localhost:8080/users/1
Content-Type: application/json
Authorization: Basic user password

###
GET http://localhost:8080/ads
Content-Type: application/json
Authorization: Basic user password


###
POST http://localhost:8080/users/set_password
Content-Type: application/json
Authorization: Basic user password

{
  "newPassword": "password",
  "currentPassword": "password1"
}

###
POST http://localhost:8080/ads
Content-Type: application/json
Authorization: Basic user password

{
  "image": "123",
  "price": 123,
  "description": "123",
  "pk": 1233,
  "title": "123"
}

###
GET http://localhost:8080/ads
Content-Type: application/json
Authorization: Basic user password


###
POST http://localhost:8080/ads
Content-Type: multipart/form-data boundary=spacer
Authorization: Basic user@gmail.com password

--spacer
Content-Disposition: form-data; name="adsDto"
Content-Type: application/json

{
  "description": "pinguin",
  "price": 340,
  "title": "selling"
}

--spacer
Content-Disposition: form-data; name="file"
Content-Type: application/octet-stream
Content-Transfer-Encoding: base64

C:/Users/Кот/Downloads/09af8ba33b9b3e503c7c359540726f15.jpg

###
POST http://localhost:8080/ads
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Basic dXNlckBnbWFpbC5jb206cGFzc3dvcmQ=

--WebAppBoundary
Content-Disposition: form-data; name="adsDto"
Content-Type: application/json

{
  "description": "pinguin",
  "price": 340,
  "title": "selling"
}
--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="09af8ba33b9b3e503c7c359540726f15.jpg"
Content-Type: image/png

< C:/Users/Кот/Downloads/09af8ba33b9b3e503c7c359540726f15.jpg
--WebAppBoundary

